#pragma once

#include "NativeGameplayTags.h"

namespace ProjectRiftGameplayTags
{
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Primary);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Dodge);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_Q);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_E);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Ability_Skill_R);

	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Role_Assault);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Role_Engineer);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Role_Medic);

	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Status_Magnitude);

	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Type_Physical);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Type_Pollution);

	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Debuff_Polluted);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Debuff_Slowed);

	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Ability_Enemy_Melee);

	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Downed);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stunned);

	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill_Q);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill_E);
	PROJECTA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill_R);
}
