#include "UI/PRMissionSelectionWidget.h"
#include "Core/PRAssetManager.h"
#include "Core/PRGameState.h"
#include "Fonts/SlateFontInfo.h"
#include "InputCoreTypes.h"
#include "Player/PRPlayerController.h"
#include "Player/PRPlayerState.h"
#include "Progression/PRMissionProgressionDataAsset.h"
#include "Widgets/Input/SButton.h"
#include "Widgets/Layout/SBorder.h"
#include "Widgets/SBoxPanel.h"
#include "Widgets/Text/STextBlock.h"
UPRMissionSelectionWidget::UPRMissionSelectionWidget(const FObjectInitializer& O):Super(O){SetIsFocusable(true);}
TSharedRef<SWidget> UPRMissionSelectionWidget::RebuildWidget(){ auto Box=SNew(SVerticalBox)+SVerticalBox::Slot().AutoHeight()[SNew(STextBlock).Text(FText::FromString(TEXT("Rift Contract Selection")))]+SVerticalBox::Slot().FillHeight(1)[SAssignNew(SummaryText,STextBlock).AutoWrapText(true)]+SVerticalBox::Slot().AutoHeight()[SNew(SHorizontalBox)+SHorizontalBox::Slot()[SNew(SButton).OnClicked_UObject(this,&UPRMissionSelectionWidget::HandlePrevious)[SNew(STextBlock).Text(FText::FromString(TEXT("Previous")))]]+SHorizontalBox::Slot()[SNew(SButton).OnClicked_UObject(this,&UPRMissionSelectionWidget::HandleNext)[SNew(STextBlock).Text(FText::FromString(TEXT("Next")))]]+SHorizontalBox::Slot()[SNew(SButton).OnClicked_UObject(this,&UPRMissionSelectionWidget::HandleSelect)[SNew(STextBlock).Text(FText::FromString(TEXT("Select")))]]+SHorizontalBox::Slot()[SNew(SButton).OnClicked_UObject(this,&UPRMissionSelectionWidget::HandleClose)[SNew(STextBlock).Text(FText::FromString(TEXT("Close")))]]]; RefreshMissionDisplay(); return SNew(SBorder).Padding(18)[Box];}
void UPRMissionSelectionWidget::RefreshMissionDisplay(){Rows.Reset(); auto* C=Cast<APRPlayerController>(GetOwningPlayer()); auto* PS=C?C->GetPlayerState<APRPlayerState>():nullptr; if(auto* AM=UPRAssetManager::Get()){TArray<UPRMissionProgressionDataAsset*> Catalog; if(AM->LoadMissionCatalog(Catalog)) for(auto* M:Catalog){FPRMissionSelectionRow R;R.ContractId=M->MissionId;R.BiomeId=M->Contract.BiomeId;R.DifficultyId=M->Contract.DifficultyId;R.ModifierIds=M->Contract.ModifierIds;R.RewardPreview=M->Contract.RewardPreview;R.bLocked=!PS||!M->IsEligible(PS->GetBoundStoryProgress());Rows.Add(R);}} if(Rows.IsValidIndex(FocusedRowIndex)==false) FocusedRowIndex=Rows.IsEmpty()?INDEX_NONE:0; if(SummaryText)SummaryText->SetText(BuildSummary());}
FText UPRMissionSelectionWidget::BuildSummary()const{if(!Rows.IsValidIndex(FocusedRowIndex))return FText::FromString(TEXT("No valid mission contracts are registered."));const auto&R=Rows[FocusedRowIndex];return FText::FromString(FString::Printf(TEXT("%d / %d\nContract: %s\nBiome: %s | Difficulty: %s\nModifiers: %s\nReward budget: %d-%d | Rarity: %d-%d\n%s"),FocusedRowIndex+1,Rows.Num(),*R.ContractId.ToString(),*R.BiomeId.ToString(),*R.DifficultyId.ToString(),*FString::JoinBy(R.ModifierIds,TEXT(", "),[](FName N){return N.ToString();}),R.RewardPreview.MinimumBudget,R.RewardPreview.MaximumBudget,R.RewardPreview.MinimumRarity,R.RewardPreview.MaximumRarity,R.bLocked?TEXT("LOCKED by chapter progression"):TEXT("Available")));}
void UPRMissionSelectionWidget::FocusNext(){if(!Rows.IsEmpty()){FocusedRowIndex=(FocusedRowIndex+1)%Rows.Num();RefreshMissionDisplay();}} void UPRMissionSelectionWidget::FocusPrevious(){if(!Rows.IsEmpty()){FocusedRowIndex=(FocusedRowIndex+Rows.Num()-1)%Rows.Num();RefreshMissionDisplay();}} void UPRMissionSelectionWidget::RequestFocusedSelection(){if(auto*C=Cast<APRPlayerController>(GetOwningPlayer());C&&Rows.IsValidIndex(FocusedRowIndex))C->SelectMissionContract(Rows[FocusedRowIndex].ContractId);} void UPRMissionSelectionWidget::RequestClose(){if(auto*C=Cast<APRPlayerController>(GetOwningPlayer()))C->HideMissionSelectionPanel();} FReply UPRMissionSelectionWidget::HandlePrevious(){FocusPrevious();return FReply::Handled();} FReply UPRMissionSelectionWidget::HandleNext(){FocusNext();return FReply::Handled();} FReply UPRMissionSelectionWidget::HandleSelect(){RequestFocusedSelection();return FReply::Handled();} FReply UPRMissionSelectionWidget::HandleClose(){RequestClose();return FReply::Handled();} FReply UPRMissionSelectionWidget::NativeOnKeyDown(const FGeometry&G,const FKeyEvent&E){if(E.GetKey()==EKeys::Escape){RequestClose();return FReply::Handled();}if(E.GetKey()==EKeys::Left){FocusPrevious();return FReply::Handled();}if(E.GetKey()==EKeys::Right){FocusNext();return FReply::Handled();}if(E.GetKey()==EKeys::Enter){RequestFocusedSelection();return FReply::Handled();}return Super::NativeOnKeyDown(G,E);}
